table:
  name: rooms
  schema: public
object_relationships:
  - name: hotel
    using:
      foreign_key_constraint_on: hotel_id
  - name: room_type
    using:
      foreign_key_constraint_on: room_type_id
  - name: images
    using:
      foreign_key_constraint_on:
        table:
          name: room_images
          schema: public
        columns:
          - room_id
select_permissions:
  - role: MANAGER
    permission:
      allow_aggregations: true
      columns:
        - room_id
        - hotel_id
        - room_number
        - room_type_id
        - price_night
        - capacity
        - status
        - created_at
        - updated_at
      filter:
        hotel:
          owner:
            firebase_uid:
              _eq: X-Hasura-User-Id
  - role: STAFF
    permission:
      allow_aggregations: true
      columns:
        - room_id
        - hotel_id
        - room_number
        - room_type_id
        - price_night
        - capacity
        - status
        - created_at
        - updated_at
      filter:
        hotel:
          owner:
            firebase_uid:
              _eq: X-Hasura-User-Id
  - role: platform_admin
    permission:
      allow_aggregations: true
      columns:
        - room_id
        - hotel_id
        - room_number
        - room_type_id
        - price_night
        - capacity
        - status
        - created_at
        - updated_at
      filter: {}