table:
  name: room_images
  schema: public
object_relationships:
  - name: room
    using:
      foreign_key_constraint_on: room_id
select_permissions:
  - role: tenant
    permission:
      columns:
        - id
        - room_id
        - image_url
        - uploaded_at
      filter: {}
  - role: landlord
    permission:
      columns:
        - id
        - room_id
        - image_url
        - uploaded_at
      filter: {}