table:
  name: room_types
  schema: public
select_permissions:
  - role: MANAGER
    permission:
      columns:
        - id
        - name
        - description
        - created_at
        - updated_at
      filter: {}
  - role: STAFF
    permission:
      columns:
        - id
        - name
        - description
        - created_at
        - updated_at
      filter: {}
  - role: platform_admin
    permission:
      columns:
        - id
        - name
        - description
        - created_at
        - updated_at
      filter: {}