- "!include hotel_industry_users.yaml"
- "!include hotel_industry_hotels.yaml"
- "!include hotel_industry_rooms.yaml"
- "!include hotel_industry_room_types.yaml"
- "!include hotel_industry_reservations.yaml"
- "!include hotel_industry_escrow_transactions.yaml"
- "!include hotel_industry_escrow_transaction_users.yaml"
- "!include hotel_industry_users_wallets.yaml"
- "!include hotel_industry_room_images.yaml"
- "!include hotel_industry_pricing_rules.yaml"
