- "!include public_hotels.yaml"
- "!include public_rooms.yaml"
- "!include public_room_types.yaml"
- "!include public_reservations.yaml"
- "!include public_escrow_transactions.yaml"
- "!include public_escrow_transaction_users.yaml"
- "!include public_user_wallets.yaml"
- "!include public_room_images.yaml"
- "!include public_pricing_rules.yaml"