version: '3.9'
services:
  hasura:
    image: hasura/graphql-engine:v2.24.0
    ports:
      - "8080:8080"
    volumes:
      - ./infra/hasura/migrations:/hasura-migrations
      - ./infra/hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_DATABASE_URL: ${PG_DATABASE_URL}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256","jwk_url":"https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com","audience":"safetrust-890d0","issuer":"https://securetoken.google.com/safetrust-890d0"}'
