import { Service } from './types';

export const services: Service[] = [
  {
    id: '1',
    title: 'Smart Contract Development',
    rating: 4.8,
    reviews: 156,
    description: 'Professional smart contract development with security audits and deployment assistance.',
    location: 'Global, Remote',
    startingPrice: 2000,
    deliveryTime: '5-10 business days',
    badges: ['Verified', 'Top Rated'],
    category: 'Development',
  },
  {
    id: '2',
    title: 'Security Audit Services',
    rating: 4.9,
    reviews: 98,
    description: 'Comprehensive security audits for smart contracts and blockchain applications.',
    location: 'United States',
    startingPrice: 1500,
    deliveryTime: '3-5 business days',
    badges: ['Certified', 'Fast Delivery'],
    category: 'Consulting',
  },
  {
    id: '3',
    title: 'Blockchain Consulting',
    rating: 4.7,
    reviews: 72,
    description: 'Expert consulting services for blockchain implementation and strategy.',
    location: 'Europe',
    startingPrice: 500,
    deliveryTime: '1-2 business days',
    badges: ['Expert', 'Available Now'],
    category: 'Consulting',
  },
  {
    id: '4',
    title: 'Smart Contract Upgrade',
    rating: 4.6,
    reviews: 45,
    description: 'Specialized in upgrading and optimizing existing smart contracts.',
    location: 'Asia Pacific',
    startingPrice: 1200,
    deliveryTime: '2-4 business days',
    badges: ['Specialized', 'Experienced'],
    category: 'Development',
  },
  {
    id: '5',
    title: 'Contract Testing Service',
    rating: 4.8,
    reviews: 89,
    description: 'Thorough testing and validation of smart contracts before deployment.',
    location: 'Global, Remote',
    startingPrice: 800,
    deliveryTime: '2-3 business days',
    badges: ['Certified', 'Reliable'],
    category: 'Development',
  },
  {
    id: '6',
    title: 'Emergency Support',
    rating: 4.9,
    reviews: 123,
    description: '24/7 emergency support for critical smart contract issues.',
    location: 'Worldwide',
    startingPrice: 3000,
    deliveryTime: 'Same day',
    badges: ['24/7', 'Priority'],
    category: 'Consulting',
  }
]; 