-- ════════════════════════════════════════════════════════════════════════════
-- Init SQL for tenant: hotel_industry
-- GENERATED by bin/generate-init-sql — DO NOT EDIT.
-- Source: infra/backend/migrations/hotel_industry up to version 1756285114000
-- Regenerate: cd infra/backend && bin/generate-init-sql hotel_industry
-- ════════════════════════════════════════════════════════════════════════════

-- ── Migration: 1723171122097_create_hotel_users

-- Schema for the hotel_industry tenant. Every hotel object lives here —
-- never in public — so the hotel_industry Hasura source has a single,
-- unambiguous home for its tables.
CREATE SCHEMA IF NOT EXISTS hotel_industry;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;

-- Shared updated_at trigger for hotel_industry tables.
CREATE OR REPLACE FUNCTION hotel_industry.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS hotel_industry.users (
    id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    firebase_uid  TEXT UNIQUE,
    email         VARCHAR(150) NOT NULL UNIQUE,
    first_name    VARCHAR(50),
    last_name     VARCHAR(50),
    phone_number  VARCHAR(20),
    role          VARCHAR(20) NOT NULL DEFAULT 'GUEST'
                    CHECK (role IN ('GUEST', 'STAFF', 'MANAGER')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hotel_industry_users_role ON hotel_industry.users (role);

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON hotel_industry.users
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- ── Migration: 1723171122098_create_hotels_table

CREATE TABLE IF NOT EXISTS hotel_industry.hotels (
    id             UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    owner_user_id  UUID NOT NULL REFERENCES hotel_industry.users(id) ON DELETE RESTRICT,
    name           VARCHAR(100) NOT NULL CHECK (char_length(trim(name)) > 0),
    description    VARCHAR(500),
    address        VARCHAR(200) NOT NULL CHECK (char_length(trim(address)) > 0),
    location_area  VARCHAR(100),
    coordinates    geometry(Point, 4326),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hotels_owner         ON hotel_industry.hotels (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_hotels_location_area ON hotel_industry.hotels (location_area);
CREATE INDEX IF NOT EXISTS idx_hotels_coordinates   ON hotel_industry.hotels USING GIST (coordinates);
CREATE INDEX IF NOT EXISTS idx_hotels_coordinates_geog ON hotel_industry.hotels USING GIST ((coordinates::geography));

CREATE TRIGGER hotels_set_updated_at
  BEFORE UPDATE ON hotel_industry.hotels
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- ── Migration: 1733171122097_create_room_types

CREATE TABLE IF NOT EXISTS hotel_industry.room_types (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name         VARCHAR(50) NOT NULL UNIQUE,
    description  TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_room_types_name ON hotel_industry.room_types (name);

CREATE TRIGGER room_types_set_updated_at
  BEFORE UPDATE ON hotel_industry.room_types
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- ── Migration: 1733171122099_create_rooms

CREATE TABLE IF NOT EXISTS hotel_industry.rooms (
    room_id       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    hotel_id      UUID NOT NULL REFERENCES hotel_industry.hotels(id) ON DELETE RESTRICT,
    room_number   VARCHAR(10) NOT NULL,
    room_type_id  UUID NOT NULL REFERENCES hotel_industry.room_types(id) ON DELETE RESTRICT,
    price_night   NUMERIC(10,2) NOT NULL CHECK (price_night > 0),
    capacity      INTEGER NOT NULL CHECK (capacity > 0),
    is_available  BOOLEAN NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT rooms_unique_number_per_hotel UNIQUE (hotel_id, room_number)
);

CREATE INDEX IF NOT EXISTS idx_rooms_hotel_id   ON hotel_industry.rooms (hotel_id);
CREATE INDEX IF NOT EXISTS idx_rooms_room_type  ON hotel_industry.rooms (room_type_id);

CREATE TRIGGER rooms_set_updated_at
  BEFORE UPDATE ON hotel_industry.rooms
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- ── Migration: 1743029389869_create_users_wallets_table

CREATE TABLE IF NOT EXISTS hotel_industry.users_wallets (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID NOT NULL REFERENCES hotel_industry.users(id) ON DELETE CASCADE,
    wallet_address  VARCHAR(255) NOT NULL,
    chain_type      VARCHAR(50) NOT NULL,
    is_primary      BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT users_wallets_address_unique UNIQUE (wallet_address)
);

CREATE INDEX IF NOT EXISTS idx_users_wallets_user_id    ON hotel_industry.users_wallets (user_id);
CREATE INDEX IF NOT EXISTS idx_users_wallets_is_primary ON hotel_industry.users_wallets (is_primary);

CREATE TRIGGER users_wallets_set_updated_at
  BEFORE UPDATE ON hotel_industry.users_wallets
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- ── Migration: 1744160264002_track_nearby_hotels_function

-- Nearby search: meters via geography; Hasura-trackable (SETOF a tracked table).
-- Parameter is named p_location_area (not location_area) so it can't be
-- confused with hotel_industry.hotels.location_area inside the query body.
CREATE OR REPLACE FUNCTION hotel_industry.find_nearby_hotels(
    lat              DOUBLE PRECISION,
    lng              DOUBLE PRECISION,
    radius_meters    DOUBLE PRECISION,
    p_location_area  TEXT DEFAULT NULL
)
RETURNS SETOF hotel_industry.hotels
LANGUAGE sql STABLE AS $$
  SELECT h.*
    FROM hotel_industry.hotels h
   WHERE h.coordinates IS NOT NULL
     AND ST_DWithin(
           h.coordinates::geography,
           ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography,
           radius_meters)
     AND (p_location_area IS NULL OR h.location_area = p_location_area)
   ORDER BY h.coordinates::geography <-> ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography;
$$;

-- ── Migration: 1745664202191_create_reservations

CREATE TABLE IF NOT EXISTS hotel_industry.reservations (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    reservation_id      UUID,
    wallet_address      VARCHAR(255),
    room_id             UUID REFERENCES hotel_industry.rooms(room_id) ON DELETE RESTRICT,
    check_in            TIMESTAMPTZ,
    check_out           TIMESTAMPTZ,
    capacity            INTEGER,
    reservation_status  VARCHAR(15) NOT NULL DEFAULT 'PENDING',
    total_amount        NUMERIC(10, 2),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reservations_wallet_address ON hotel_industry.reservations (wallet_address);
CREATE INDEX IF NOT EXISTS idx_reservations_room_id        ON hotel_industry.reservations (room_id);
CREATE INDEX IF NOT EXISTS idx_reservations_status          ON hotel_industry.reservations (reservation_status);
CREATE INDEX IF NOT EXISTS idx_reservations_dates           ON hotel_industry.reservations (check_in, check_out);

CREATE TRIGGER reservations_set_updated_at
  BEFORE UPDATE ON hotel_industry.reservations
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- ── Migration: 1745664202192_create_escrow_transactions

CREATE TABLE IF NOT EXISTS hotel_industry.escrow_transactions (
    id                       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    reservation_id           UUID REFERENCES hotel_industry.reservations(id) ON DELETE RESTRICT,
    contract_id              TEXT UNIQUE,
    escrow_status            VARCHAR(200) NOT NULL DEFAULT 'PENDING',
    signer_address           VARCHAR(200),
    transaction_type         VARCHAR(150),
    escrow_transaction_type  VARCHAR(150),
    http_status_code         INTEGER,
    escrow_payload           JSONB,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_escrow_transactions_reservation ON hotel_industry.escrow_transactions (reservation_id);
CREATE INDEX IF NOT EXISTS idx_escrow_transactions_status      ON hotel_industry.escrow_transactions (escrow_status);
CREATE INDEX IF NOT EXISTS idx_escrow_transactions_type        ON hotel_industry.escrow_transactions (transaction_type);
CREATE INDEX IF NOT EXISTS idx_escrow_transactions_created_at  ON hotel_industry.escrow_transactions (created_at);

CREATE TRIGGER escrow_transactions_set_updated_at
  BEFORE UPDATE ON hotel_industry.escrow_transactions
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- ── Migration: 1745664202193_create_escrow_transaction_users

CREATE TABLE IF NOT EXISTS hotel_industry.escrow_transaction_users (
    id                     UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_email             VARCHAR(150) REFERENCES hotel_industry.users(email) ON DELETE RESTRICT,
    escrow_transaction_id  UUID REFERENCES hotel_industry.escrow_transactions(id) ON DELETE CASCADE,
    role                   VARCHAR(20),
    status                 VARCHAR(20),
    is_primary             BOOLEAN NOT NULL DEFAULT false,
    funded_at              TIMESTAMPTZ,
    funding_status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_escrow_user_role UNIQUE (escrow_transaction_id, user_email, role)
);

CREATE INDEX IF NOT EXISTS idx_escrow_transaction_users_transaction_id ON hotel_industry.escrow_transaction_users (escrow_transaction_id);
CREATE INDEX IF NOT EXISTS idx_escrow_transaction_users_user_email     ON hotel_industry.escrow_transaction_users (user_email);
CREATE INDEX IF NOT EXISTS idx_escrow_transaction_users_funding_status ON hotel_industry.escrow_transaction_users (funding_status);

CREATE TRIGGER escrow_transaction_users_set_updated_at
  BEFORE UPDATE ON hotel_industry.escrow_transaction_users
  FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- Payload sent to TrustlessWork's fund-escrow API, tracked per transaction.
ALTER TABLE hotel_industry.escrow_transactions ADD COLUMN IF NOT EXISTS fund_payload JSONB;

-- ── Migration: 1746439500253_create-room-images

CREATE TABLE IF NOT EXISTS hotel_industry.room_images (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    room_id      UUID NOT NULL REFERENCES hotel_industry.rooms(room_id) ON DELETE CASCADE,
    image_url    VARCHAR(150) NOT NULL,
    uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_room_images_room_id ON hotel_industry.room_images (room_id);

-- ── Migration: 1756195007000_create_top_rooms_function

-- Create function to get top 5 most reserved rooms
CREATE OR REPLACE FUNCTION hotel_industry.get_top_rooms_by_reservations(
    time_period VARCHAR DEFAULT 'all',
    filter_status VARCHAR DEFAULT NULL
)
RETURNS TABLE (
    room_id UUID,
    room_number VARCHAR(10),
    hotel_name VARCHAR(100),
    reservation_count BIGINT,
    total_revenue NUMERIC(12,2)
) AS $$
DECLARE
    date_filter TIMESTAMPTZ;
BEGIN
    -- Validate time_period parameter
    IF time_period NOT IN ('week', 'month', 'year', 'all') THEN
        RAISE EXCEPTION 'Invalid time_period. Must be one of: week, month, year, all';
    END IF;

    -- Calculate date filter based on time_period
    CASE time_period
        WHEN 'week' THEN
            date_filter := NOW() - INTERVAL '1 week';
        WHEN 'month' THEN
            date_filter := NOW() - INTERVAL '1 month';
        WHEN 'year' THEN
            date_filter := NOW() - INTERVAL '1 year';
        ELSE
            date_filter := '1970-01-01'::TIMESTAMPTZ; -- Beginning of time for 'all'
    END CASE;

    RETURN QUERY
    SELECT
        r.room_id,
        r.room_number,
        h.name as hotel_name,
        COUNT(res.id) as reservation_count,
        COALESCE(SUM(res.total_amount), 0) as total_revenue
    FROM hotel_industry.rooms r
    INNER JOIN hotel_industry.hotels h ON r.hotel_id = h.id
    LEFT JOIN hotel_industry.reservations res ON r.room_id = res.room_id
        AND res.created_at >= date_filter
        AND (filter_status IS NULL OR res.reservation_status = filter_status)
    GROUP BY r.room_id, r.room_number, h.name
    HAVING COUNT(res.id) > 0  -- Only include rooms with reservations
    ORDER BY reservation_count DESC, total_revenue DESC
    LIMIT 5;
END;
$$ LANGUAGE plpgsql STABLE;

-- ── Migration: 1756285113000_create_pricing_rules

-- Create Hotel Industry pricing rules table
CREATE TABLE hotel_industry.pricing_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rule_name VARCHAR(100) NOT NULL,
    rule_type VARCHAR(50) NOT NULL,        -- 'ROOM_DEPOSIT', 'BOOKING_FEE', 'CANCELLATION_FEE', 'SERVICE_FEE', 'SEASONAL_RATE'
    currency VARCHAR(10) NOT NULL,         -- 'USD', 'EUR', 'USDC', etc.
    
    -- Pricing configuration
    base_amount DECIMAL(20,7) DEFAULT 0,   -- Fixed fee amount
    percentage DECIMAL(5,4) DEFAULT 0,     -- Percentage fee (e.g., 0.050 = 5%)
    min_amount DECIMAL(20,7) DEFAULT 0,    -- Minimum fee amount
    max_amount DECIMAL(20,7) DEFAULT 999999999, -- Maximum fee amount
    
    -- Hotel-specific fields
    room_type VARCHAR(50),                 -- 'STANDARD', 'DELUXE', 'SUITE', 'PRESIDENTIAL'
    season VARCHAR(30),                    -- 'HIGH_SEASON', 'LOW_SEASON', 'PEAK', 'OFF_PEAK'
    advance_booking_days INTEGER,          -- Days in advance for early booking discounts
    
    -- Rule management
    priority INTEGER DEFAULT 100,          -- Lower number = higher priority
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Ensure unique rule per type/currency combination
    CONSTRAINT unique_hotel_rule_type_currency UNIQUE (rule_type, currency, room_type, season)
);

-- Performance indexes for common query patterns
CREATE INDEX idx_hotel_pricing_rules_type_currency_active 
ON hotel_industry.pricing_rules(rule_type, currency, is_active)
WHERE is_active = true;

CREATE INDEX idx_hotel_pricing_rules_room_season 
ON hotel_industry.pricing_rules(room_type, season, is_active)
WHERE is_active = true;

CREATE INDEX idx_hotel_pricing_rules_priority 
ON hotel_industry.pricing_rules(priority, is_active)
WHERE is_active = true;

CREATE INDEX idx_hotel_pricing_rules_advance_booking 
ON hotel_industry.pricing_rules(advance_booking_days, is_active)
WHERE is_active = true AND advance_booking_days IS NOT NULL;

-- Auto-update timestamp trigger
CREATE TRIGGER update_hotel_pricing_rules_updated_at
    BEFORE UPDATE ON hotel_industry.pricing_rules
    FOR EACH ROW EXECUTE FUNCTION hotel_industry.set_updated_at();

-- Add helpful comment
COMMENT ON TABLE hotel_industry.pricing_rules IS 
'Pricing rules for Hotel Industry tenant - supports room deposits, booking fees, seasonal rates, and hospitality-specific pricing models';
-- ── Migration: 1756285114000_hotel_schema_contract

-- Enforce hotel schema contract
ALTER TABLE hotels ALTER COLUMN name TYPE VARCHAR(100);
ALTER TABLE hotels ALTER COLUMN address TYPE VARCHAR(200);
ALTER TABLE hotels ALTER COLUMN description TYPE VARCHAR(500);
ALTER TABLE hotels ALTER COLUMN location_area TYPE VARCHAR(100);

-- Add owner_user_id column referencing users(id) with RESTRICT
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS owner_user_id UUID REFERENCES users(id) ON DELETE RESTRICT;

-- Index owner_user_id
CREATE INDEX IF NOT EXISTS idx_hotels_owner_user_id ON hotels(owner_user_id);

-- Enforce ON DELETE RESTRICT on rooms -> hotels (prevent cascading deletes)
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS rooms_hotel_id_fkey;
ALTER TABLE rooms ADD CONSTRAINT rooms_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE RESTRICT;

-- Ensure trigger hotels_set_updated_at maintains updated_at
CREATE OR REPLACE FUNCTION hotels_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_updated_at ON hotels;
DROP TRIGGER IF EXISTS hotels_set_updated_at ON hotels;

CREATE TRIGGER hotels_set_updated_at
BEFORE UPDATE ON hotels
FOR EACH ROW
EXECUTE FUNCTION hotels_set_updated_at();
