actions:
  - name: sendVerificationCode
    definition:
      kind: synchronous
      handler: http://192.168.0.167:3000/send-verification
      forward_client_headers: true
    permissions:
      - role: anonymous
  - name: verifyEmailCode
    definition:
      kind: synchronous
      handler: http://localhost:3000/verify-code
      forward_client_headers: true
    permissions:
      - role: anonymous
  - name: prepare_escrow_contract
    definition:
      kind: synchronous
      handler: http://webhook:3000/prepare-escrow-contract
      forward_client_headers: true
    permissions:
      - role: user
        permission:
          allow: true
  - name: open_dispute
    definition:
      kind: synchronous
      handler: '{{WEBHOOK_URL}}/api/escrow/dispute'
      headers:
        - name: x-hasura-admin-secret
          value_from_env: WEBHOOK_ADMIN_SECRET
      forward_client_headers: true
    permissions:
      - role: user
        permission:
          allow: true

custom_types:
  enums: []
  input_objects:
    - name: SendVerificationInput
    - name: VerifyCodeInput
  objects:
    - name: VerificationResponse
  scalars: []