table:
  name: roles
  schema: public
array_relationships:
  - name: user_roles
    using:
      foreign_key_constraint_on:
        column: role_id
        table:
          name: user_roles
          schema: public
select_permissions:
  - role: tenant
    permission:
      columns:
        - id
        - name
        - description
      filter: {}
  - role: landlord
    permission:
      columns:
        - id
        - name
        - description
      filter: {}
